"""empty message

Revision ID: d5e9ddf637a1
Revises: 
Create Date: 2022-05-29 12:39:20.204410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5e9ddf637a1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book', sa.String(length=255), nullable=True),
    sa.Column('reading', sa.Boolean(), nullable=True),
    sa.Column('had_read', sa.Boolean(), nullable=True),
    sa.Column('to_read', sa.Boolean(), nullable=True),
    sa.Column('img_path', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('book')
    # ### end Alembic commands ###
